# Author : Solomon Broadbent throw-an-email@sol-the.dev


"ui.background" = { bg = "background" }
"ui.selection" = { bg = "selection_background" }

string = "green"
# constant = "white"
# "constant.builtin" = "white"
"constant.numeric" = "numbers"
special = "purple"
variables = "variables"
"variable.parameter" = { fg = "#FFFFFF", modifiers = ["underlined"] }
"variable.builtin" = "variables"
# keywords = "keywords"
function = "functions"
"function.macro" = "functions"
"function.builtin" = "functions"
tag = "tags"
punctuation = "operators"
"punctuation.delimiter" = "operators"
label = "variables"

[palette]
background = "#263238"
foreground = "#b0bec5"
text = "#607d8b"
selection_background = "#546e7a"
selection_foreground = "#ffffff"
buttons = "#2e3c43"
second_background = "#32424a"
disabled = "#415967"
contrast = "#1e272c"
active = "#314549"
border = "#2a373e"
highlight = "#425b67"
tree = "#546e7a70"
notifications = "#1e272c"
accent = "#009688"
excluded_files = "#2e3c43"

green = "#c3e88d"
yellow = "#ffcb6b"
blue = "#82aaff"
red = "#f07178"
purple = "#c792ea"
orange = "#f78c6c"
cyan = "#89ddff"
gray = "#546e7a"
white = "#ffffff"
black = "#eeffff"
error = "#ff5370"

comments = "#546e7a"
variables = "#eeffff"
links = "#80cbc4"
functions = "#82aaff"
keywords = "#c792ea"
tags = "#f07178"
strings = "#c3e88d"
operators = "#89ddff"
attributes = "#ffcb6b"
numbers = "#f78c6c"
parameters = "#f78c6c"
